# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/myint/autoflake
    rev: v2.1.1
    hooks:
    -   id: autoflake
        args:
            - --in-place
            - --ignore-init-module-imports
            - --remove-unused-variables
            - --remove-all-unused-imports
            - --expand-star-imports
            - --recursive
            - src
-   repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
    -   id: isort
        args: [--remove-unused-imports]
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.3.0"
    hooks:
    -   id: mypy
        args: [ --strict-optional, --ignore-missing-imports ]
